/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PL.LoginHome.StudentAccount;

import PL.LoginHome.LoginStudent;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author slimane
 */
public class StudentDashboard extends javax.swing.JFrame {

    /**
     * Creates new form StudentDashboard
     */
    
    int idStudent;
    public StudentDashboard() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        resultBtn = new javax.swing.JLabel();
        MyFreindsBtn = new javax.swing.JLabel();
        MyProfileBtn = new javax.swing.JLabel();
        writeRapportBtn = new javax.swing.JLabel();
        MyTeachersBtn = new javax.swing.JLabel();
        AdvertisementsBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1290, 661));

        jPanel1.setBackground(new java.awt.Color(235, 233, 233));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(60, 92, 227)));
        jPanel1.setPreferredSize(new java.awt.Dimension(1290, 680));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/StudentDashboard.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 120));

        jPanel2.setBackground(new java.awt.Color(108, 149, 234));
        jPanel2.setBorder(null);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Student Portal");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 12, 253, 56));

        jPanel5.setBackground(new java.awt.Color(254, 254, 254));
        jPanel5.setBorder(null);
        jPanel5.setPreferredSize(new java.awt.Dimension(116, 40));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel5MouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(108, 149, 234));
        jLabel6.setText("Logout");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, 40));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1025, 20, 102, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 1250, 80));

        jPanel3.setBackground(new java.awt.Color(108, 149, 234));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(42, 102, 226)));

        jLabel2.setFont(new java.awt.Font("Andika", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Welcome");

        jLabel3.setFont(new java.awt.Font("Andika", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("to");

        jLabel4.setFont(new java.awt.Font("URW Gothic L", 0, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Student Dashboard");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(22, 22, 22))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 280, 380));

        jPanel4.setBackground(new java.awt.Color(254, 254, 254));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 33, 33)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resultBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/resultDefault_1.png"))); // NOI18N
        resultBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resultBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                resultBtnMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resultBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resultBtnMouseEntered(evt);
            }
        });
        jPanel4.add(resultBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 270, 150));

        MyFreindsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/MyfreindDefault.png"))); // NOI18N
        MyFreindsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MyFreindsBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MyFreindsBtnMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyFreindsBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MyFreindsBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MyFreindsBtnMouseEntered(evt);
            }
        });
        jPanel4.add(MyFreindsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 270, 150));

        MyProfileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/MyProfileDefault.png"))); // NOI18N
        MyProfileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MyProfileBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MyProfileBtnMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyProfileBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MyProfileBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MyProfileBtnMouseEntered(evt);
            }
        });
        jPanel4.add(MyProfileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 270, 150));

        writeRapportBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/writeRapportDefault.png"))); // NOI18N
        writeRapportBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                writeRapportBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                writeRapportBtnMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                writeRapportBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                writeRapportBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                writeRapportBtnMouseEntered(evt);
            }
        });
        jPanel4.add(writeRapportBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 270, 150));

        MyTeachersBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/MyTeachersDefault.png"))); // NOI18N
        MyTeachersBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MyTeachersBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MyTeachersBtnMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyTeachersBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MyTeachersBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MyTeachersBtnMouseEntered(evt);
            }
        });
        jPanel4.add(MyTeachersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 270, 150));

        AdvertisementsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/advertisementsDefault.png"))); // NOI18N
        AdvertisementsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AdvertisementsBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AdvertisementsBtnMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdvertisementsBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdvertisementsBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdvertisementsBtnMouseEntered(evt);
            }
        });
        jPanel4.add(AdvertisementsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 270, 150));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 940, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1289, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resultBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultBtnMouseEntered
        ImageIcon ii = new ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/resultOnEntred.png"));
        resultBtn.setIcon(ii);
    }//GEN-LAST:event_resultBtnMouseEntered

    private void resultBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultBtnMouseExited
        ImageIcon ii = new ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/resultDefault_1.png"));
        resultBtn.setIcon(ii);
    }//GEN-LAST:event_resultBtnMouseExited

    private void resultBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultBtnMousePressed
        ImageIcon ii = new ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/resultOnClicked.png"));
        resultBtn.setIcon(ii);
    }//GEN-LAST:event_resultBtnMousePressed

    private void resultBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultBtnMouseReleased
        ImageIcon ii =  new ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/resultDefault_1.png"));
        resultBtn.setIcon(ii);
    }//GEN-LAST:event_resultBtnMouseReleased

    private void MyFreindsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyFreindsBtnMouseEntered
       ImageIcon ii =  new ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/MyFreindsOnEntred.png"));
       MyFreindsBtn.setIcon(ii);
    }//GEN-LAST:event_MyFreindsBtnMouseEntered

    private void MyFreindsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyFreindsBtnMouseExited
        ImageIcon ii =  new ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/MyfreindDefault.png"));
        MyFreindsBtn.setIcon(ii);
    }//GEN-LAST:event_MyFreindsBtnMouseExited

    private void MyFreindsBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyFreindsBtnMousePressed
       ImageIcon ii =  new ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/MyFreindsOnClicked.png"));
       MyFreindsBtn.setIcon(ii);
    }//GEN-LAST:event_MyFreindsBtnMousePressed

    private void MyFreindsBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyFreindsBtnMouseReleased
       ImageIcon ii =  new ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/MyfreindDefault.png"));
       MyFreindsBtn.setIcon(ii);
    }//GEN-LAST:event_MyFreindsBtnMouseReleased

    private void MyProfileBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyProfileBtnMouseEntered
       ImageIcon ii =  new ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/MyProfileOnEntred.png"));
       MyProfileBtn.setIcon(ii);
    }//GEN-LAST:event_MyProfileBtnMouseEntered

    private void MyProfileBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyProfileBtnMouseExited
       ImageIcon ii =  new ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/MyProfileDefault.png"));
       MyProfileBtn.setIcon(ii);
    }//GEN-LAST:event_MyProfileBtnMouseExited

    private void MyProfileBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyProfileBtnMousePressed
       ImageIcon ii =  new ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/MyProfileOnClicked.png"));
       MyProfileBtn.setIcon(ii);
    }//GEN-LAST:event_MyProfileBtnMousePressed

    private void MyProfileBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyProfileBtnMouseReleased
       ImageIcon ii =  new ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/MyProfileDefault.png"));
       MyProfileBtn.setIcon(ii);
    }//GEN-LAST:event_MyProfileBtnMouseReleased

    private void writeRapportBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_writeRapportBtnMouseEntered
       ImageIcon ii =  new ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/writeRapportOnEntred.png"));
       writeRapportBtn.setIcon(ii);
    }//GEN-LAST:event_writeRapportBtnMouseEntered

    private void writeRapportBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_writeRapportBtnMouseExited
       ImageIcon ii =  new ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/writeRapportDefault.png"));
       writeRapportBtn.setIcon(ii);
    }//GEN-LAST:event_writeRapportBtnMouseExited

    private void writeRapportBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_writeRapportBtnMousePressed
       ImageIcon ii =  new ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/writeRapportOnClicked.png"));
       writeRapportBtn.setIcon(ii);
    }//GEN-LAST:event_writeRapportBtnMousePressed

    private void writeRapportBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_writeRapportBtnMouseReleased
       ImageIcon ii =  new ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/writeRapportDefault.png"));
       writeRapportBtn.setIcon(ii);
    }//GEN-LAST:event_writeRapportBtnMouseReleased

    private void MyTeachersBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyTeachersBtnMouseEntered
       ImageIcon ii =  new ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/MyTeachersOnEntred.png"));
       MyTeachersBtn.setIcon(ii);
    }//GEN-LAST:event_MyTeachersBtnMouseEntered

    private void MyTeachersBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyTeachersBtnMouseExited
       ImageIcon ii =  new ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/MyTeachersDefault.png"));
       MyTeachersBtn.setIcon(ii);
    }//GEN-LAST:event_MyTeachersBtnMouseExited

    private void MyTeachersBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyTeachersBtnMousePressed
       ImageIcon ii =  new ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/MyTeachersOnClicked.png"));
       MyTeachersBtn.setIcon(ii);
    }//GEN-LAST:event_MyTeachersBtnMousePressed

    private void MyTeachersBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyTeachersBtnMouseReleased
       ImageIcon ii =  new ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/MyTeachersDefault.png"));
       MyTeachersBtn.setIcon(ii);
    }//GEN-LAST:event_MyTeachersBtnMouseReleased

    private void AdvertisementsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdvertisementsBtnMouseEntered
       ImageIcon ii =  new ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/advertisementsOnEntred.png"));
       AdvertisementsBtn.setIcon(ii);
    }//GEN-LAST:event_AdvertisementsBtnMouseEntered

    private void AdvertisementsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdvertisementsBtnMouseExited
       ImageIcon ii =  new ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/advertisementsDefault.png"));
       AdvertisementsBtn.setIcon(ii);
    }//GEN-LAST:event_AdvertisementsBtnMouseExited

    private void AdvertisementsBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdvertisementsBtnMousePressed
       ImageIcon ii =  new ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/advertisementsOnClicked.png"));
       AdvertisementsBtn.setIcon(ii);
    }//GEN-LAST:event_AdvertisementsBtnMousePressed

    private void AdvertisementsBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdvertisementsBtnMouseReleased
       ImageIcon ii =  new ImageIcon(getClass().getResource("/PL/LoginHome/StudentAccount/StudentImages/advertisementsDefault.png"));
       AdvertisementsBtn.setIcon(ii);
    }//GEN-LAST:event_AdvertisementsBtnMouseReleased

    private void resultBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultBtnMouseClicked
       new Result().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_resultBtnMouseClicked

    private void MyFreindsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyFreindsBtnMouseClicked
        new MyFreinds().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MyFreindsBtnMouseClicked

    private void MyProfileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyProfileBtnMouseClicked
       new MyProfile().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_MyProfileBtnMouseClicked

    private void writeRapportBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_writeRapportBtnMouseClicked
       new writeRapport().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_writeRapportBtnMouseClicked

    private void MyTeachersBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyTeachersBtnMouseClicked
       new MyTeachers().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_MyTeachersBtnMouseClicked

    private void AdvertisementsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdvertisementsBtnMouseClicked
       new Advertisements().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_AdvertisementsBtnMouseClicked

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
       jPanel5.setBackground(new Color(254,254,254));
       jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        new LoginStudent().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
       jPanel5.setBackground(new Color(231,231,231));
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseReleased
        jPanel5.setBackground(new Color(254, 254, 254));
    }//GEN-LAST:event_jPanel5MouseReleased

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
       jPanel5.setBackground(new Color(241, 241, 241));
       jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(WIDTH));
    }//GEN-LAST:event_jPanel5MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdvertisementsBtn;
    private javax.swing.JLabel MyFreindsBtn;
    private javax.swing.JLabel MyProfileBtn;
    private javax.swing.JLabel MyTeachersBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel resultBtn;
    private javax.swing.JLabel writeRapportBtn;
    // End of variables declaration//GEN-END:variables
}
